### ISSUE TITLE
Rollerhouse support

### ISSUE THREAD

**Issue by ahaverty** [sillyfrog/homie_blind_control#2]
@sillyfrog thanks for sharing this project!

I've got a [Rollerhouse motor](https://www.amazon.co.uk/Rollerhouse-Electric-Curtains-Rechargeable-Motorized/dp/B07NV4L1W9), and what seems to be a BF-305 ([this one exactly](https://www.amazon.co.uk/dp/B077P7YWQH?th=1)).

_I slowly discovered this week that my Broadlink RM4Pro does not fit the job for the rolling code problem._
I was just wondering before I go buying more hardware, would you expect your library and hardware from the readme, to work for my setup?

Thanks so much!

**Comment by sillyfrog** [comment]
It’s hard to say unfortunately. That motor and remote look identical to some I use I got from AliExpress, so there’s a good chance. 

However this will always send the same code and it does not “roll”. 

What issue are you having? Is it just not reliable, or does it totally stop working with the Broaink?

**Comment by ahaverty** [comment]
Ah, I misunderstood what this library was then, sorry.
My issue is the rollerhouse motor has some kind of rolling code security. So sending the same code twice in a row will not work the second time.
I've since worked around this somehow, by just brute-force blasting it with ~50 unique codes on repeat with the broadlink, (I manually learnt ~50 codes for each command). It's consistently _eventually_ is happy with one of the codes within about max 20-30 seconds. So I'll probably just live with this solution for now 😅
Thanks for getting back to me, sorry I missed your notification back in November.
